// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package mailgun.kafkapixy;

public interface ConsumerPartitionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ConsumerPartitions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 partitions = 1;</code>
   * @return A list containing the partitions.
   */
  java.util.List<java.lang.Integer> getPartitionsList();
  /**
   * <code>repeated int32 partitions = 1;</code>
   * @return The count of partitions.
   */
  int getPartitionsCount();
  /**
   * <code>repeated int32 partitions = 1;</code>
   * @param index The index of the element to return.
   * @return The partitions at the given index.
   */
  int getPartitions(int index);
}
