// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package mailgun.kafkapixy;

/**
 * Protobuf type {@code GetOffsetsRs}
 */
public final class GetOffsetsRs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetOffsetsRs)
    GetOffsetsRsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetOffsetsRs.newBuilder() to construct.
  private GetOffsetsRs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetOffsetsRs() {
    offsets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetOffsetsRs();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetOffsetsRs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              offsets_ = new java.util.ArrayList<mailgun.kafkapixy.PartitionOffset>();
              mutable_bitField0_ |= 0x00000001;
            }
            offsets_.add(
                input.readMessage(mailgun.kafkapixy.PartitionOffset.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        offsets_ = java.util.Collections.unmodifiableList(offsets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetOffsetsRs_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetOffsetsRs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mailgun.kafkapixy.GetOffsetsRs.class, mailgun.kafkapixy.GetOffsetsRs.Builder.class);
  }

  public static final int OFFSETS_FIELD_NUMBER = 1;
  private java.util.List<mailgun.kafkapixy.PartitionOffset> offsets_;
  /**
   * <code>repeated .PartitionOffset offsets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<mailgun.kafkapixy.PartitionOffset> getOffsetsList() {
    return offsets_;
  }
  /**
   * <code>repeated .PartitionOffset offsets = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends mailgun.kafkapixy.PartitionOffsetOrBuilder> 
      getOffsetsOrBuilderList() {
    return offsets_;
  }
  /**
   * <code>repeated .PartitionOffset offsets = 1;</code>
   */
  @java.lang.Override
  public int getOffsetsCount() {
    return offsets_.size();
  }
  /**
   * <code>repeated .PartitionOffset offsets = 1;</code>
   */
  @java.lang.Override
  public mailgun.kafkapixy.PartitionOffset getOffsets(int index) {
    return offsets_.get(index);
  }
  /**
   * <code>repeated .PartitionOffset offsets = 1;</code>
   */
  @java.lang.Override
  public mailgun.kafkapixy.PartitionOffsetOrBuilder getOffsetsOrBuilder(
      int index) {
    return offsets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < offsets_.size(); i++) {
      output.writeMessage(1, offsets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < offsets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, offsets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mailgun.kafkapixy.GetOffsetsRs)) {
      return super.equals(obj);
    }
    mailgun.kafkapixy.GetOffsetsRs other = (mailgun.kafkapixy.GetOffsetsRs) obj;

    if (!getOffsetsList()
        .equals(other.getOffsetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOffsetsCount() > 0) {
      hash = (37 * hash) + OFFSETS_FIELD_NUMBER;
      hash = (53 * hash) + getOffsetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.GetOffsetsRs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mailgun.kafkapixy.GetOffsetsRs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetOffsetsRs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetOffsetsRs)
      mailgun.kafkapixy.GetOffsetsRsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetOffsetsRs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetOffsetsRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mailgun.kafkapixy.GetOffsetsRs.class, mailgun.kafkapixy.GetOffsetsRs.Builder.class);
    }

    // Construct using mailgun.kafkapixy.GetOffsetsRs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOffsetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (offsetsBuilder_ == null) {
        offsets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        offsetsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetOffsetsRs_descriptor;
    }

    @java.lang.Override
    public mailgun.kafkapixy.GetOffsetsRs getDefaultInstanceForType() {
      return mailgun.kafkapixy.GetOffsetsRs.getDefaultInstance();
    }

    @java.lang.Override
    public mailgun.kafkapixy.GetOffsetsRs build() {
      mailgun.kafkapixy.GetOffsetsRs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mailgun.kafkapixy.GetOffsetsRs buildPartial() {
      mailgun.kafkapixy.GetOffsetsRs result = new mailgun.kafkapixy.GetOffsetsRs(this);
      int from_bitField0_ = bitField0_;
      if (offsetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          offsets_ = java.util.Collections.unmodifiableList(offsets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.offsets_ = offsets_;
      } else {
        result.offsets_ = offsetsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mailgun.kafkapixy.GetOffsetsRs) {
        return mergeFrom((mailgun.kafkapixy.GetOffsetsRs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mailgun.kafkapixy.GetOffsetsRs other) {
      if (other == mailgun.kafkapixy.GetOffsetsRs.getDefaultInstance()) return this;
      if (offsetsBuilder_ == null) {
        if (!other.offsets_.isEmpty()) {
          if (offsets_.isEmpty()) {
            offsets_ = other.offsets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOffsetsIsMutable();
            offsets_.addAll(other.offsets_);
          }
          onChanged();
        }
      } else {
        if (!other.offsets_.isEmpty()) {
          if (offsetsBuilder_.isEmpty()) {
            offsetsBuilder_.dispose();
            offsetsBuilder_ = null;
            offsets_ = other.offsets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            offsetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOffsetsFieldBuilder() : null;
          } else {
            offsetsBuilder_.addAllMessages(other.offsets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mailgun.kafkapixy.GetOffsetsRs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mailgun.kafkapixy.GetOffsetsRs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<mailgun.kafkapixy.PartitionOffset> offsets_ =
      java.util.Collections.emptyList();
    private void ensureOffsetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        offsets_ = new java.util.ArrayList<mailgun.kafkapixy.PartitionOffset>(offsets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mailgun.kafkapixy.PartitionOffset, mailgun.kafkapixy.PartitionOffset.Builder, mailgun.kafkapixy.PartitionOffsetOrBuilder> offsetsBuilder_;

    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public java.util.List<mailgun.kafkapixy.PartitionOffset> getOffsetsList() {
      if (offsetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(offsets_);
      } else {
        return offsetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public int getOffsetsCount() {
      if (offsetsBuilder_ == null) {
        return offsets_.size();
      } else {
        return offsetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public mailgun.kafkapixy.PartitionOffset getOffsets(int index) {
      if (offsetsBuilder_ == null) {
        return offsets_.get(index);
      } else {
        return offsetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder setOffsets(
        int index, mailgun.kafkapixy.PartitionOffset value) {
      if (offsetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffsetsIsMutable();
        offsets_.set(index, value);
        onChanged();
      } else {
        offsetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder setOffsets(
        int index, mailgun.kafkapixy.PartitionOffset.Builder builderForValue) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.set(index, builderForValue.build());
        onChanged();
      } else {
        offsetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder addOffsets(mailgun.kafkapixy.PartitionOffset value) {
      if (offsetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffsetsIsMutable();
        offsets_.add(value);
        onChanged();
      } else {
        offsetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder addOffsets(
        int index, mailgun.kafkapixy.PartitionOffset value) {
      if (offsetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffsetsIsMutable();
        offsets_.add(index, value);
        onChanged();
      } else {
        offsetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder addOffsets(
        mailgun.kafkapixy.PartitionOffset.Builder builderForValue) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.add(builderForValue.build());
        onChanged();
      } else {
        offsetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder addOffsets(
        int index, mailgun.kafkapixy.PartitionOffset.Builder builderForValue) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.add(index, builderForValue.build());
        onChanged();
      } else {
        offsetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder addAllOffsets(
        java.lang.Iterable<? extends mailgun.kafkapixy.PartitionOffset> values) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, offsets_);
        onChanged();
      } else {
        offsetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder clearOffsets() {
      if (offsetsBuilder_ == null) {
        offsets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        offsetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public Builder removeOffsets(int index) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.remove(index);
        onChanged();
      } else {
        offsetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public mailgun.kafkapixy.PartitionOffset.Builder getOffsetsBuilder(
        int index) {
      return getOffsetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public mailgun.kafkapixy.PartitionOffsetOrBuilder getOffsetsOrBuilder(
        int index) {
      if (offsetsBuilder_ == null) {
        return offsets_.get(index);  } else {
        return offsetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public java.util.List<? extends mailgun.kafkapixy.PartitionOffsetOrBuilder> 
         getOffsetsOrBuilderList() {
      if (offsetsBuilder_ != null) {
        return offsetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(offsets_);
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public mailgun.kafkapixy.PartitionOffset.Builder addOffsetsBuilder() {
      return getOffsetsFieldBuilder().addBuilder(
          mailgun.kafkapixy.PartitionOffset.getDefaultInstance());
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public mailgun.kafkapixy.PartitionOffset.Builder addOffsetsBuilder(
        int index) {
      return getOffsetsFieldBuilder().addBuilder(
          index, mailgun.kafkapixy.PartitionOffset.getDefaultInstance());
    }
    /**
     * <code>repeated .PartitionOffset offsets = 1;</code>
     */
    public java.util.List<mailgun.kafkapixy.PartitionOffset.Builder> 
         getOffsetsBuilderList() {
      return getOffsetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mailgun.kafkapixy.PartitionOffset, mailgun.kafkapixy.PartitionOffset.Builder, mailgun.kafkapixy.PartitionOffsetOrBuilder> 
        getOffsetsFieldBuilder() {
      if (offsetsBuilder_ == null) {
        offsetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mailgun.kafkapixy.PartitionOffset, mailgun.kafkapixy.PartitionOffset.Builder, mailgun.kafkapixy.PartitionOffsetOrBuilder>(
                offsets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        offsets_ = null;
      }
      return offsetsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetOffsetsRs)
  }

  // @@protoc_insertion_point(class_scope:GetOffsetsRs)
  private static final mailgun.kafkapixy.GetOffsetsRs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mailgun.kafkapixy.GetOffsetsRs();
  }

  public static mailgun.kafkapixy.GetOffsetsRs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetOffsetsRs>
      PARSER = new com.google.protobuf.AbstractParser<GetOffsetsRs>() {
    @java.lang.Override
    public GetOffsetsRs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetOffsetsRs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetOffsetsRs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetOffsetsRs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mailgun.kafkapixy.GetOffsetsRs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

