// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package mailgun.kafkapixy;

/**
 * Protobuf type {@code GetTopicMetadataRs}
 */
public final class GetTopicMetadataRs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetTopicMetadataRs)
    GetTopicMetadataRsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTopicMetadataRs.newBuilder() to construct.
  private GetTopicMetadataRs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTopicMetadataRs() {
    partitions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTopicMetadataRs();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTopicMetadataRs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            version_ = input.readInt32();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              config_ = com.google.protobuf.MapField.newMapField(
                  ConfigDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            config__ = input.readMessage(
                ConfigDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            config_.getMutableMap().put(
                config__.getKey(), config__.getValue());
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              partitions_ = new java.util.ArrayList<mailgun.kafkapixy.PartitionMetadata>();
              mutable_bitField0_ |= 0x00000002;
            }
            partitions_.add(
                input.readMessage(mailgun.kafkapixy.PartitionMetadata.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        partitions_ = java.util.Collections.unmodifiableList(partitions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetTopicMetadataRs_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 2:
        return internalGetConfig();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetTopicMetadataRs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mailgun.kafkapixy.GetTopicMetadataRs.class, mailgun.kafkapixy.GetTopicMetadataRs.Builder.class);
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private int version_;
  /**
   * <pre>
   * Version of this metadata
   * </pre>
   *
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int CONFIG_FIELD_NUMBER = 2;
  private static final class ConfigDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                mailgun.kafkapixy.KafkaPixyProto.internal_static_GetTopicMetadataRs_ConfigEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> config_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetConfig() {
    if (config_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ConfigDefaultEntryHolder.defaultEntry);
    }
    return config_;
  }

  public int getConfigCount() {
    return internalGetConfig().getMap().size();
  }
  /**
   * <pre>
   * Config values
   * </pre>
   *
   * <code>map&lt;string, string&gt; config = 2;</code>
   */

  @java.lang.Override
  public boolean containsConfig(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetConfig().getMap().containsKey(key);
  }
  /**
   * Use {@link #getConfigMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getConfig() {
    return getConfigMap();
  }
  /**
   * <pre>
   * Config values
   * </pre>
   *
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getConfigMap() {
    return internalGetConfig().getMap();
  }
  /**
   * <pre>
   * Config values
   * </pre>
   *
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getConfigOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetConfig().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Config values
   * </pre>
   *
   * <code>map&lt;string, string&gt; config = 2;</code>
   */
  @java.lang.Override

  public java.lang.String getConfigOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetConfig().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PARTITIONS_FIELD_NUMBER = 3;
  private java.util.List<mailgun.kafkapixy.PartitionMetadata> partitions_;
  /**
   * <pre>
   * Optional list of metadata for the partitions of this topic
   * </pre>
   *
   * <code>repeated .PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<mailgun.kafkapixy.PartitionMetadata> getPartitionsList() {
    return partitions_;
  }
  /**
   * <pre>
   * Optional list of metadata for the partitions of this topic
   * </pre>
   *
   * <code>repeated .PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends mailgun.kafkapixy.PartitionMetadataOrBuilder> 
      getPartitionsOrBuilderList() {
    return partitions_;
  }
  /**
   * <pre>
   * Optional list of metadata for the partitions of this topic
   * </pre>
   *
   * <code>repeated .PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public int getPartitionsCount() {
    return partitions_.size();
  }
  /**
   * <pre>
   * Optional list of metadata for the partitions of this topic
   * </pre>
   *
   * <code>repeated .PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public mailgun.kafkapixy.PartitionMetadata getPartitions(int index) {
    return partitions_.get(index);
  }
  /**
   * <pre>
   * Optional list of metadata for the partitions of this topic
   * </pre>
   *
   * <code>repeated .PartitionMetadata partitions = 3;</code>
   */
  @java.lang.Override
  public mailgun.kafkapixy.PartitionMetadataOrBuilder getPartitionsOrBuilder(
      int index) {
    return partitions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (version_ != 0) {
      output.writeInt32(1, version_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetConfig(),
        ConfigDefaultEntryHolder.defaultEntry,
        2);
    for (int i = 0; i < partitions_.size(); i++) {
      output.writeMessage(3, partitions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, version_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetConfig().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      config__ = ConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, config__);
    }
    for (int i = 0; i < partitions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, partitions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mailgun.kafkapixy.GetTopicMetadataRs)) {
      return super.equals(obj);
    }
    mailgun.kafkapixy.GetTopicMetadataRs other = (mailgun.kafkapixy.GetTopicMetadataRs) obj;

    if (getVersion()
        != other.getVersion()) return false;
    if (!internalGetConfig().equals(
        other.internalGetConfig())) return false;
    if (!getPartitionsList()
        .equals(other.getPartitionsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    if (!internalGetConfig().getMap().isEmpty()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + internalGetConfig().hashCode();
    }
    if (getPartitionsCount() > 0) {
      hash = (37 * hash) + PARTITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.GetTopicMetadataRs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mailgun.kafkapixy.GetTopicMetadataRs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetTopicMetadataRs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetTopicMetadataRs)
      mailgun.kafkapixy.GetTopicMetadataRsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetTopicMetadataRs_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetTopicMetadataRs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mailgun.kafkapixy.GetTopicMetadataRs.class, mailgun.kafkapixy.GetTopicMetadataRs.Builder.class);
    }

    // Construct using mailgun.kafkapixy.GetTopicMetadataRs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPartitionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = 0;

      internalGetMutableConfig().clear();
      if (partitionsBuilder_ == null) {
        partitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        partitionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_GetTopicMetadataRs_descriptor;
    }

    @java.lang.Override
    public mailgun.kafkapixy.GetTopicMetadataRs getDefaultInstanceForType() {
      return mailgun.kafkapixy.GetTopicMetadataRs.getDefaultInstance();
    }

    @java.lang.Override
    public mailgun.kafkapixy.GetTopicMetadataRs build() {
      mailgun.kafkapixy.GetTopicMetadataRs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mailgun.kafkapixy.GetTopicMetadataRs buildPartial() {
      mailgun.kafkapixy.GetTopicMetadataRs result = new mailgun.kafkapixy.GetTopicMetadataRs(this);
      int from_bitField0_ = bitField0_;
      result.version_ = version_;
      result.config_ = internalGetConfig();
      result.config_.makeImmutable();
      if (partitionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          partitions_ = java.util.Collections.unmodifiableList(partitions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.partitions_ = partitions_;
      } else {
        result.partitions_ = partitionsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mailgun.kafkapixy.GetTopicMetadataRs) {
        return mergeFrom((mailgun.kafkapixy.GetTopicMetadataRs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mailgun.kafkapixy.GetTopicMetadataRs other) {
      if (other == mailgun.kafkapixy.GetTopicMetadataRs.getDefaultInstance()) return this;
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      internalGetMutableConfig().mergeFrom(
          other.internalGetConfig());
      if (partitionsBuilder_ == null) {
        if (!other.partitions_.isEmpty()) {
          if (partitions_.isEmpty()) {
            partitions_ = other.partitions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePartitionsIsMutable();
            partitions_.addAll(other.partitions_);
          }
          onChanged();
        }
      } else {
        if (!other.partitions_.isEmpty()) {
          if (partitionsBuilder_.isEmpty()) {
            partitionsBuilder_.dispose();
            partitionsBuilder_ = null;
            partitions_ = other.partitions_;
            bitField0_ = (bitField0_ & ~0x00000002);
            partitionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionsFieldBuilder() : null;
          } else {
            partitionsBuilder_.addAllMessages(other.partitions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mailgun.kafkapixy.GetTopicMetadataRs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mailgun.kafkapixy.GetTopicMetadataRs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int version_ ;
    /**
     * <pre>
     * Version of this metadata
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * Version of this metadata
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version of this metadata
     * </pre>
     *
     * <code>int32 version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> config_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetConfig() {
      if (config_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ConfigDefaultEntryHolder.defaultEntry);
      }
      return config_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableConfig() {
      onChanged();;
      if (config_ == null) {
        config_ = com.google.protobuf.MapField.newMapField(
            ConfigDefaultEntryHolder.defaultEntry);
      }
      if (!config_.isMutable()) {
        config_ = config_.copy();
      }
      return config_;
    }

    public int getConfigCount() {
      return internalGetConfig().getMap().size();
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */

    @java.lang.Override
    public boolean containsConfig(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetConfig().getMap().containsKey(key);
    }
    /**
     * Use {@link #getConfigMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getConfig() {
      return getConfigMap();
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getConfigMap() {
      return internalGetConfig().getMap();
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getConfigOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetConfig().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getConfigOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetConfig().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearConfig() {
      internalGetMutableConfig().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */

    public Builder removeConfig(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableConfig().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableConfig() {
      return internalGetMutableConfig().getMutableMap();
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */
    public Builder putConfig(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableConfig().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Config values
     * </pre>
     *
     * <code>map&lt;string, string&gt; config = 2;</code>
     */

    public Builder putAllConfig(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableConfig().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.util.List<mailgun.kafkapixy.PartitionMetadata> partitions_ =
      java.util.Collections.emptyList();
    private void ensurePartitionsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        partitions_ = new java.util.ArrayList<mailgun.kafkapixy.PartitionMetadata>(partitions_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mailgun.kafkapixy.PartitionMetadata, mailgun.kafkapixy.PartitionMetadata.Builder, mailgun.kafkapixy.PartitionMetadataOrBuilder> partitionsBuilder_;

    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public java.util.List<mailgun.kafkapixy.PartitionMetadata> getPartitionsList() {
      if (partitionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partitions_);
      } else {
        return partitionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public int getPartitionsCount() {
      if (partitionsBuilder_ == null) {
        return partitions_.size();
      } else {
        return partitionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public mailgun.kafkapixy.PartitionMetadata getPartitions(int index) {
      if (partitionsBuilder_ == null) {
        return partitions_.get(index);
      } else {
        return partitionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder setPartitions(
        int index, mailgun.kafkapixy.PartitionMetadata value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.set(index, value);
        onChanged();
      } else {
        partitionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder setPartitions(
        int index, mailgun.kafkapixy.PartitionMetadata.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(mailgun.kafkapixy.PartitionMetadata value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.add(value);
        onChanged();
      } else {
        partitionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(
        int index, mailgun.kafkapixy.PartitionMetadata value) {
      if (partitionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionsIsMutable();
        partitions_.add(index, value);
        onChanged();
      } else {
        partitionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(
        mailgun.kafkapixy.PartitionMetadata.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.add(builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder addPartitions(
        int index, mailgun.kafkapixy.PartitionMetadata.Builder builderForValue) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder addAllPartitions(
        java.lang.Iterable<? extends mailgun.kafkapixy.PartitionMetadata> values) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partitions_);
        onChanged();
      } else {
        partitionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder clearPartitions() {
      if (partitionsBuilder_ == null) {
        partitions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        partitionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public Builder removePartitions(int index) {
      if (partitionsBuilder_ == null) {
        ensurePartitionsIsMutable();
        partitions_.remove(index);
        onChanged();
      } else {
        partitionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public mailgun.kafkapixy.PartitionMetadata.Builder getPartitionsBuilder(
        int index) {
      return getPartitionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public mailgun.kafkapixy.PartitionMetadataOrBuilder getPartitionsOrBuilder(
        int index) {
      if (partitionsBuilder_ == null) {
        return partitions_.get(index);  } else {
        return partitionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public java.util.List<? extends mailgun.kafkapixy.PartitionMetadataOrBuilder> 
         getPartitionsOrBuilderList() {
      if (partitionsBuilder_ != null) {
        return partitionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partitions_);
      }
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public mailgun.kafkapixy.PartitionMetadata.Builder addPartitionsBuilder() {
      return getPartitionsFieldBuilder().addBuilder(
          mailgun.kafkapixy.PartitionMetadata.getDefaultInstance());
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public mailgun.kafkapixy.PartitionMetadata.Builder addPartitionsBuilder(
        int index) {
      return getPartitionsFieldBuilder().addBuilder(
          index, mailgun.kafkapixy.PartitionMetadata.getDefaultInstance());
    }
    /**
     * <pre>
     * Optional list of metadata for the partitions of this topic
     * </pre>
     *
     * <code>repeated .PartitionMetadata partitions = 3;</code>
     */
    public java.util.List<mailgun.kafkapixy.PartitionMetadata.Builder> 
         getPartitionsBuilderList() {
      return getPartitionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mailgun.kafkapixy.PartitionMetadata, mailgun.kafkapixy.PartitionMetadata.Builder, mailgun.kafkapixy.PartitionMetadataOrBuilder> 
        getPartitionsFieldBuilder() {
      if (partitionsBuilder_ == null) {
        partitionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mailgun.kafkapixy.PartitionMetadata, mailgun.kafkapixy.PartitionMetadata.Builder, mailgun.kafkapixy.PartitionMetadataOrBuilder>(
                partitions_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        partitions_ = null;
      }
      return partitionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetTopicMetadataRs)
  }

  // @@protoc_insertion_point(class_scope:GetTopicMetadataRs)
  private static final mailgun.kafkapixy.GetTopicMetadataRs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mailgun.kafkapixy.GetTopicMetadataRs();
  }

  public static mailgun.kafkapixy.GetTopicMetadataRs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTopicMetadataRs>
      PARSER = new com.google.protobuf.AbstractParser<GetTopicMetadataRs>() {
    @java.lang.Override
    public GetTopicMetadataRs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTopicMetadataRs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTopicMetadataRs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTopicMetadataRs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mailgun.kafkapixy.GetTopicMetadataRs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

