// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package mailgun.kafkapixy;

public interface GetTopicMetadataRqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTopicMetadataRq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The cluster.
   */
  java.lang.String getCluster();
  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The bytes for cluster.
   */
  com.google.protobuf.ByteString
      getClusterBytes();

  /**
   * <pre>
   * Name of a topic
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <pre>
   * Name of a topic
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * Should include partition metadata
   * </pre>
   *
   * <code>bool with_partitions = 3;</code>
   * @return The withPartitions.
   */
  boolean getWithPartitions();
}
