// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package mailgun.kafkapixy;

/**
 * Protobuf type {@code SetOffsetsRq}
 */
public final class SetOffsetsRq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SetOffsetsRq)
    SetOffsetsRqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SetOffsetsRq.newBuilder() to construct.
  private SetOffsetsRq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SetOffsetsRq() {
    cluster_ = "";
    topic_ = "";
    group_ = "";
    offsets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SetOffsetsRq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SetOffsetsRq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cluster_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            group_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              offsets_ = new java.util.ArrayList<mailgun.kafkapixy.PartitionOffset>();
              mutable_bitField0_ |= 0x00000001;
            }
            offsets_.add(
                input.readMessage(mailgun.kafkapixy.PartitionOffset.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        offsets_ = java.util.Collections.unmodifiableList(offsets_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mailgun.kafkapixy.KafkaPixyProto.internal_static_SetOffsetsRq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mailgun.kafkapixy.KafkaPixyProto.internal_static_SetOffsetsRq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mailgun.kafkapixy.SetOffsetsRq.class, mailgun.kafkapixy.SetOffsetsRq.Builder.class);
  }

  public static final int CLUSTER_FIELD_NUMBER = 1;
  private volatile java.lang.Object cluster_;
  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The cluster.
   */
  @java.lang.Override
  public java.lang.String getCluster() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cluster_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The bytes for cluster.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClusterBytes() {
    java.lang.Object ref = cluster_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cluster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 2;
  private volatile java.lang.Object topic_;
  /**
   * <pre>
   * Name of a topic
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of a topic
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_FIELD_NUMBER = 3;
  private volatile java.lang.Object group_;
  /**
   * <pre>
   * Name of a consumer group.
   * </pre>
   *
   * <code>string group = 3;</code>
   * @return The group.
   */
  @java.lang.Override
  public java.lang.String getGroup() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of a consumer group.
   * </pre>
   *
   * <code>string group = 3;</code>
   * @return The bytes for group.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupBytes() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFSETS_FIELD_NUMBER = 4;
  private java.util.List<mailgun.kafkapixy.PartitionOffset> offsets_;
  /**
   * <code>repeated .PartitionOffset offsets = 4;</code>
   */
  @java.lang.Override
  public java.util.List<mailgun.kafkapixy.PartitionOffset> getOffsetsList() {
    return offsets_;
  }
  /**
   * <code>repeated .PartitionOffset offsets = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends mailgun.kafkapixy.PartitionOffsetOrBuilder> 
      getOffsetsOrBuilderList() {
    return offsets_;
  }
  /**
   * <code>repeated .PartitionOffset offsets = 4;</code>
   */
  @java.lang.Override
  public int getOffsetsCount() {
    return offsets_.size();
  }
  /**
   * <code>repeated .PartitionOffset offsets = 4;</code>
   */
  @java.lang.Override
  public mailgun.kafkapixy.PartitionOffset getOffsets(int index) {
    return offsets_.get(index);
  }
  /**
   * <code>repeated .PartitionOffset offsets = 4;</code>
   */
  @java.lang.Override
  public mailgun.kafkapixy.PartitionOffsetOrBuilder getOffsetsOrBuilder(
      int index) {
    return offsets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClusterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cluster_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
    }
    if (!getGroupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, group_);
    }
    for (int i = 0; i < offsets_.size(); i++) {
      output.writeMessage(4, offsets_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClusterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cluster_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
    }
    if (!getGroupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, group_);
    }
    for (int i = 0; i < offsets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, offsets_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof mailgun.kafkapixy.SetOffsetsRq)) {
      return super.equals(obj);
    }
    mailgun.kafkapixy.SetOffsetsRq other = (mailgun.kafkapixy.SetOffsetsRq) obj;

    if (!getCluster()
        .equals(other.getCluster())) return false;
    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getGroup()
        .equals(other.getGroup())) return false;
    if (!getOffsetsList()
        .equals(other.getOffsetsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
    hash = (53 * hash) + getCluster().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    if (getOffsetsCount() > 0) {
      hash = (37 * hash) + OFFSETS_FIELD_NUMBER;
      hash = (53 * hash) + getOffsetsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mailgun.kafkapixy.SetOffsetsRq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mailgun.kafkapixy.SetOffsetsRq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SetOffsetsRq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SetOffsetsRq)
      mailgun.kafkapixy.SetOffsetsRqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_SetOffsetsRq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_SetOffsetsRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mailgun.kafkapixy.SetOffsetsRq.class, mailgun.kafkapixy.SetOffsetsRq.Builder.class);
    }

    // Construct using mailgun.kafkapixy.SetOffsetsRq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOffsetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cluster_ = "";

      topic_ = "";

      group_ = "";

      if (offsetsBuilder_ == null) {
        offsets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        offsetsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mailgun.kafkapixy.KafkaPixyProto.internal_static_SetOffsetsRq_descriptor;
    }

    @java.lang.Override
    public mailgun.kafkapixy.SetOffsetsRq getDefaultInstanceForType() {
      return mailgun.kafkapixy.SetOffsetsRq.getDefaultInstance();
    }

    @java.lang.Override
    public mailgun.kafkapixy.SetOffsetsRq build() {
      mailgun.kafkapixy.SetOffsetsRq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mailgun.kafkapixy.SetOffsetsRq buildPartial() {
      mailgun.kafkapixy.SetOffsetsRq result = new mailgun.kafkapixy.SetOffsetsRq(this);
      int from_bitField0_ = bitField0_;
      result.cluster_ = cluster_;
      result.topic_ = topic_;
      result.group_ = group_;
      if (offsetsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          offsets_ = java.util.Collections.unmodifiableList(offsets_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.offsets_ = offsets_;
      } else {
        result.offsets_ = offsetsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof mailgun.kafkapixy.SetOffsetsRq) {
        return mergeFrom((mailgun.kafkapixy.SetOffsetsRq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(mailgun.kafkapixy.SetOffsetsRq other) {
      if (other == mailgun.kafkapixy.SetOffsetsRq.getDefaultInstance()) return this;
      if (!other.getCluster().isEmpty()) {
        cluster_ = other.cluster_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        onChanged();
      }
      if (offsetsBuilder_ == null) {
        if (!other.offsets_.isEmpty()) {
          if (offsets_.isEmpty()) {
            offsets_ = other.offsets_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOffsetsIsMutable();
            offsets_.addAll(other.offsets_);
          }
          onChanged();
        }
      } else {
        if (!other.offsets_.isEmpty()) {
          if (offsetsBuilder_.isEmpty()) {
            offsetsBuilder_.dispose();
            offsetsBuilder_ = null;
            offsets_ = other.offsets_;
            bitField0_ = (bitField0_ & ~0x00000001);
            offsetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOffsetsFieldBuilder() : null;
          } else {
            offsetsBuilder_.addAllMessages(other.offsets_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      mailgun.kafkapixy.SetOffsetsRq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (mailgun.kafkapixy.SetOffsetsRq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object cluster_ = "";
    /**
     * <pre>
     * Name of a Kafka cluster
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @return The cluster.
     */
    public java.lang.String getCluster() {
      java.lang.Object ref = cluster_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of a Kafka cluster
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @return The bytes for cluster.
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      java.lang.Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of a Kafka cluster
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @param value The cluster to set.
     * @return This builder for chaining.
     */
    public Builder setCluster(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a Kafka cluster
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCluster() {
      
      cluster_ = getDefaultInstance().getCluster();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a Kafka cluster
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @param value The bytes for cluster to set.
     * @return This builder for chaining.
     */
    public Builder setClusterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cluster_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <pre>
     * Name of a topic
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of a topic
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of a topic
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a topic
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a topic
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object group_ = "";
    /**
     * <pre>
     * Name of a consumer group.
     * </pre>
     *
     * <code>string group = 3;</code>
     * @return The group.
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of a consumer group.
     * </pre>
     *
     * <code>string group = 3;</code>
     * @return The bytes for group.
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of a consumer group.
     * </pre>
     *
     * <code>string group = 3;</code>
     * @param value The group to set.
     * @return This builder for chaining.
     */
    public Builder setGroup(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a consumer group.
     * </pre>
     *
     * <code>string group = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroup() {
      
      group_ = getDefaultInstance().getGroup();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a consumer group.
     * </pre>
     *
     * <code>string group = 3;</code>
     * @param value The bytes for group to set.
     * @return This builder for chaining.
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      group_ = value;
      onChanged();
      return this;
    }

    private java.util.List<mailgun.kafkapixy.PartitionOffset> offsets_ =
      java.util.Collections.emptyList();
    private void ensureOffsetsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        offsets_ = new java.util.ArrayList<mailgun.kafkapixy.PartitionOffset>(offsets_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mailgun.kafkapixy.PartitionOffset, mailgun.kafkapixy.PartitionOffset.Builder, mailgun.kafkapixy.PartitionOffsetOrBuilder> offsetsBuilder_;

    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public java.util.List<mailgun.kafkapixy.PartitionOffset> getOffsetsList() {
      if (offsetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(offsets_);
      } else {
        return offsetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public int getOffsetsCount() {
      if (offsetsBuilder_ == null) {
        return offsets_.size();
      } else {
        return offsetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public mailgun.kafkapixy.PartitionOffset getOffsets(int index) {
      if (offsetsBuilder_ == null) {
        return offsets_.get(index);
      } else {
        return offsetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder setOffsets(
        int index, mailgun.kafkapixy.PartitionOffset value) {
      if (offsetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffsetsIsMutable();
        offsets_.set(index, value);
        onChanged();
      } else {
        offsetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder setOffsets(
        int index, mailgun.kafkapixy.PartitionOffset.Builder builderForValue) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.set(index, builderForValue.build());
        onChanged();
      } else {
        offsetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder addOffsets(mailgun.kafkapixy.PartitionOffset value) {
      if (offsetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffsetsIsMutable();
        offsets_.add(value);
        onChanged();
      } else {
        offsetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder addOffsets(
        int index, mailgun.kafkapixy.PartitionOffset value) {
      if (offsetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOffsetsIsMutable();
        offsets_.add(index, value);
        onChanged();
      } else {
        offsetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder addOffsets(
        mailgun.kafkapixy.PartitionOffset.Builder builderForValue) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.add(builderForValue.build());
        onChanged();
      } else {
        offsetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder addOffsets(
        int index, mailgun.kafkapixy.PartitionOffset.Builder builderForValue) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.add(index, builderForValue.build());
        onChanged();
      } else {
        offsetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder addAllOffsets(
        java.lang.Iterable<? extends mailgun.kafkapixy.PartitionOffset> values) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, offsets_);
        onChanged();
      } else {
        offsetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder clearOffsets() {
      if (offsetsBuilder_ == null) {
        offsets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        offsetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public Builder removeOffsets(int index) {
      if (offsetsBuilder_ == null) {
        ensureOffsetsIsMutable();
        offsets_.remove(index);
        onChanged();
      } else {
        offsetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public mailgun.kafkapixy.PartitionOffset.Builder getOffsetsBuilder(
        int index) {
      return getOffsetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public mailgun.kafkapixy.PartitionOffsetOrBuilder getOffsetsOrBuilder(
        int index) {
      if (offsetsBuilder_ == null) {
        return offsets_.get(index);  } else {
        return offsetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public java.util.List<? extends mailgun.kafkapixy.PartitionOffsetOrBuilder> 
         getOffsetsOrBuilderList() {
      if (offsetsBuilder_ != null) {
        return offsetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(offsets_);
      }
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public mailgun.kafkapixy.PartitionOffset.Builder addOffsetsBuilder() {
      return getOffsetsFieldBuilder().addBuilder(
          mailgun.kafkapixy.PartitionOffset.getDefaultInstance());
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public mailgun.kafkapixy.PartitionOffset.Builder addOffsetsBuilder(
        int index) {
      return getOffsetsFieldBuilder().addBuilder(
          index, mailgun.kafkapixy.PartitionOffset.getDefaultInstance());
    }
    /**
     * <code>repeated .PartitionOffset offsets = 4;</code>
     */
    public java.util.List<mailgun.kafkapixy.PartitionOffset.Builder> 
         getOffsetsBuilderList() {
      return getOffsetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mailgun.kafkapixy.PartitionOffset, mailgun.kafkapixy.PartitionOffset.Builder, mailgun.kafkapixy.PartitionOffsetOrBuilder> 
        getOffsetsFieldBuilder() {
      if (offsetsBuilder_ == null) {
        offsetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mailgun.kafkapixy.PartitionOffset, mailgun.kafkapixy.PartitionOffset.Builder, mailgun.kafkapixy.PartitionOffsetOrBuilder>(
                offsets_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        offsets_ = null;
      }
      return offsetsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SetOffsetsRq)
  }

  // @@protoc_insertion_point(class_scope:SetOffsetsRq)
  private static final mailgun.kafkapixy.SetOffsetsRq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mailgun.kafkapixy.SetOffsetsRq();
  }

  public static mailgun.kafkapixy.SetOffsetsRq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SetOffsetsRq>
      PARSER = new com.google.protobuf.AbstractParser<SetOffsetsRq>() {
    @java.lang.Override
    public SetOffsetsRq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SetOffsetsRq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SetOffsetsRq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SetOffsetsRq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mailgun.kafkapixy.SetOffsetsRq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

