// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package mailgun.kafkapixy;

public interface SetOffsetsRsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SetOffsetsRs)
    com.google.protobuf.MessageOrBuilder {
}
