// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

public interface AckRsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AckRs)
    com.google.protobuf.MessageOrBuilder {
}
