// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

/**
 * Protobuf type {@code ConsumerGroups}
 */
public final class ConsumerGroups extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ConsumerGroups)
    ConsumerGroupsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConsumerGroups.newBuilder() to construct.
  private ConsumerGroups(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConsumerGroups() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConsumerGroups();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConsumerGroups(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              consumers_ = com.google.protobuf.MapField.newMapField(
                  ConsumersDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<String, ConsumerPartitions>
            consumers__ = input.readMessage(
                ConsumersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            consumers_.getMutableMap().put(
                consumers__.getKey(), consumers__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Kafkapixy.internal_static_ConsumerGroups_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetConsumers();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Kafkapixy.internal_static_ConsumerGroups_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ConsumerGroups.class, ConsumerGroups.Builder.class);
  }

  public static final int CONSUMERS_FIELD_NUMBER = 1;
  private static final class ConsumersDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, ConsumerPartitions> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, ConsumerPartitions>newDefaultInstance(
                Kafkapixy.internal_static_ConsumerGroups_ConsumersEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                ConsumerPartitions.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, ConsumerPartitions> consumers_;
  private com.google.protobuf.MapField<String, ConsumerPartitions>
  internalGetConsumers() {
    if (consumers_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ConsumersDefaultEntryHolder.defaultEntry);
    }
    return consumers_;
  }

  public int getConsumersCount() {
    return internalGetConsumers().getMap().size();
  }
  /**
   * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
   */

  @Override
  public boolean containsConsumers(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetConsumers().getMap().containsKey(key);
  }
  /**
   * Use {@link #getConsumersMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, ConsumerPartitions> getConsumers() {
    return getConsumersMap();
  }
  /**
   * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
   */
  @Override

  public java.util.Map<String, ConsumerPartitions> getConsumersMap() {
    return internalGetConsumers().getMap();
  }
  /**
   * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
   */
  @Override

  public ConsumerPartitions getConsumersOrDefault(
      String key,
      ConsumerPartitions defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, ConsumerPartitions> map =
        internalGetConsumers().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
   */
  @Override

  public ConsumerPartitions getConsumersOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, ConsumerPartitions> map =
        internalGetConsumers().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetConsumers(),
        ConsumersDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<String, ConsumerPartitions> entry
         : internalGetConsumers().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, ConsumerPartitions>
      consumers__ = ConsumersDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, consumers__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ConsumerGroups)) {
      return super.equals(obj);
    }
    ConsumerGroups other = (ConsumerGroups) obj;

    if (!internalGetConsumers().equals(
        other.internalGetConsumers())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetConsumers().getMap().isEmpty()) {
      hash = (37 * hash) + CONSUMERS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetConsumers().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ConsumerGroups parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ConsumerGroups parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ConsumerGroups parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ConsumerGroups parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ConsumerGroups parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ConsumerGroups parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ConsumerGroups parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ConsumerGroups parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ConsumerGroups parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ConsumerGroups parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ConsumerGroups parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ConsumerGroups parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ConsumerGroups prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ConsumerGroups}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ConsumerGroups)
      ConsumerGroupsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Kafkapixy.internal_static_ConsumerGroups_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetConsumers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableConsumers();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Kafkapixy.internal_static_ConsumerGroups_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ConsumerGroups.class, ConsumerGroups.Builder.class);
    }

    // Construct using com.csvw.lib.ConsumerGroups.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      internalGetMutableConsumers().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Kafkapixy.internal_static_ConsumerGroups_descriptor;
    }

    @Override
    public ConsumerGroups getDefaultInstanceForType() {
      return ConsumerGroups.getDefaultInstance();
    }

    @Override
    public ConsumerGroups build() {
      ConsumerGroups result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ConsumerGroups buildPartial() {
      ConsumerGroups result = new ConsumerGroups(this);
      int from_bitField0_ = bitField0_;
      result.consumers_ = internalGetConsumers();
      result.consumers_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ConsumerGroups) {
        return mergeFrom((ConsumerGroups)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ConsumerGroups other) {
      if (other == ConsumerGroups.getDefaultInstance()) return this;
      internalGetMutableConsumers().mergeFrom(
          other.internalGetConsumers());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ConsumerGroups parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ConsumerGroups) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        String, ConsumerPartitions> consumers_;
    private com.google.protobuf.MapField<String, ConsumerPartitions>
    internalGetConsumers() {
      if (consumers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ConsumersDefaultEntryHolder.defaultEntry);
      }
      return consumers_;
    }
    private com.google.protobuf.MapField<String, ConsumerPartitions>
    internalGetMutableConsumers() {
      onChanged();;
      if (consumers_ == null) {
        consumers_ = com.google.protobuf.MapField.newMapField(
            ConsumersDefaultEntryHolder.defaultEntry);
      }
      if (!consumers_.isMutable()) {
        consumers_ = consumers_.copy();
      }
      return consumers_;
    }

    public int getConsumersCount() {
      return internalGetConsumers().getMap().size();
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */

    @Override
    public boolean containsConsumers(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetConsumers().getMap().containsKey(key);
    }
    /**
     * Use {@link #getConsumersMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, ConsumerPartitions> getConsumers() {
      return getConsumersMap();
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */
    @Override

    public java.util.Map<String, ConsumerPartitions> getConsumersMap() {
      return internalGetConsumers().getMap();
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */
    @Override

    public ConsumerPartitions getConsumersOrDefault(
        String key,
        ConsumerPartitions defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, ConsumerPartitions> map =
          internalGetConsumers().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */
    @Override

    public ConsumerPartitions getConsumersOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, ConsumerPartitions> map =
          internalGetConsumers().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearConsumers() {
      internalGetMutableConsumers().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */

    public Builder removeConsumers(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableConsumers().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, ConsumerPartitions>
    getMutableConsumers() {
      return internalGetMutableConsumers().getMutableMap();
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */
    public Builder putConsumers(
        String key,
        ConsumerPartitions value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableConsumers().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .ConsumerPartitions&gt; consumers = 1;</code>
     */

    public Builder putAllConsumers(
        java.util.Map<String, ConsumerPartitions> values) {
      internalGetMutableConsumers().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ConsumerGroups)
  }

  // @@protoc_insertion_point(class_scope:ConsumerGroups)
  private static final ConsumerGroups DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ConsumerGroups();
  }

  public static ConsumerGroups getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConsumerGroups>
      PARSER = new com.google.protobuf.AbstractParser<ConsumerGroups>() {
    @Override
    public ConsumerGroups parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConsumerGroups(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConsumerGroups> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ConsumerGroups> getParserForType() {
    return PARSER;
  }

  @Override
  public ConsumerGroups getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

