// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

public final class Kafkapixy {
  private Kafkapixy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RecordHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RecordHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProdRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProdRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProdRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProdRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsNAckRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsNAckRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartitionOffset_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartitionOffset_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOffsetsRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetOffsetsRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetOffsetsRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetOffsetsRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartitionMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartitionMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTopicMetadataRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTopicMetadataRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTopicMetadataRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTopicMetadataRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetTopicMetadataRs_ConfigEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetTopicMetadataRs_ConfigEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListTopicRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListTopicRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListTopicRs_TopicsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListTopicRs_TopicsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListTopicRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListTopicRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListConsumersRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListConsumersRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsumerPartitions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsumerPartitions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsumerGroups_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsumerGroups_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConsumerGroups_ConsumersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConsumerGroups_ConsumersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListConsumersRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListConsumersRs_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListConsumersRs_GroupsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListConsumersRs_GroupsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetOffsetsRq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetOffsetsRq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SetOffsetsRs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SetOffsetsRs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017kafkapixy.proto\"*\n\014RecordHeader\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\014\"\227\001\n\006ProdRq\022\017\n\007clus" +
      "ter\030\001 \001(\t\022\r\n\005topic\030\002 \001(\t\022\021\n\tkey_value\030\003 " +
      "\001(\014\022\025\n\rkey_undefined\030\004 \001(\010\022\017\n\007message\030\005 " +
      "\001(\014\022\022\n\nasync_mode\030\006 \001(\010\022\036\n\007headers\030\007 \003(\013" +
      "2\r.RecordHeader\"+\n\006ProdRs\022\021\n\tpartition\030\001" +
      " \001(\005\022\016\n\006offset\030\002 \001(\003\"\210\001\n\nConsNAckRq\022\017\n\007c" +
      "luster\030\001 \001(\t\022\r\n\005topic\030\002 \001(\t\022\r\n\005group\030\003 \001" +
      "(\t\022\016\n\006no_ack\030\004 \001(\010\022\020\n\010auto_ack\030\005 \001(\010\022\025\n\r" +
      "ack_partition\030\006 \001(\005\022\022\n\nack_offset\030\007 \001(\003\"" +
      "\206\001\n\006ConsRs\022\021\n\tpartition\030\001 \001(\005\022\016\n\006offset\030" +
      "\002 \001(\003\022\021\n\tkey_value\030\003 \001(\014\022\025\n\rkey_undefine" +
      "d\030\004 \001(\010\022\017\n\007message\030\005 \001(\014\022\036\n\007headers\030\006 \003(" +
      "\0132\r.RecordHeader\"Y\n\005AckRq\022\017\n\007cluster\030\001 \001" +
      "(\t\022\r\n\005topic\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022\021\n\tpart" +
      "ition\030\004 \001(\005\022\016\n\006offset\030\005 \001(\003\"\007\n\005AckRs\"\223\001\n" +
      "\017PartitionOffset\022\021\n\tpartition\030\001 \001(\005\022\r\n\005b" +
      "egin\030\002 \001(\003\022\013\n\003end\030\003 \001(\003\022\r\n\005count\030\004 \001(\003\022\016" +
      "\n\006offset\030\005 \001(\003\022\013\n\003lag\030\006 \001(\003\022\020\n\010metadata\030" +
      "\007 \001(\t\022\023\n\013sparse_acks\030\010 \001(\t\"=\n\014GetOffsets" +
      "Rq\022\017\n\007cluster\030\001 \001(\t\022\r\n\005topic\030\002 \001(\t\022\r\n\005gr" +
      "oup\030\003 \001(\t\"1\n\014GetOffsetsRs\022!\n\007offsets\030\001 \003" +
      "(\0132\020.PartitionOffset\"U\n\021PartitionMetadat" +
      "a\022\021\n\tpartition\030\001 \001(\005\022\016\n\006leader\030\002 \001(\005\022\020\n\010" +
      "replicas\030\003 \003(\005\022\013\n\003isr\030\004 \003(\005\"M\n\022GetTopicM" +
      "etadataRq\022\017\n\007cluster\030\001 \001(\t\022\r\n\005topic\030\002 \001(" +
      "\t\022\027\n\017with_partitions\030\003 \001(\010\"\255\001\n\022GetTopicM" +
      "etadataRs\022\017\n\007version\030\001 \001(\005\022/\n\006config\030\002 \003" +
      "(\0132\037.GetTopicMetadataRs.ConfigEntry\022&\n\np" +
      "artitions\030\003 \003(\0132\022.PartitionMetadata\032-\n\013C" +
      "onfigEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\002" +
      "8\001\"{\n\013ListTopicRs\022(\n\006topics\030\001 \003(\0132\030.List" +
      "TopicRs.TopicsEntry\032B\n\013TopicsEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\"\n\005value\030\002 \001(\0132\023.GetTopicMetadat" +
      "aRs:\0028\001\"7\n\013ListTopicRq\022\017\n\007cluster\030\001 \001(\t\022" +
      "\027\n\017with_partitions\030\002 \001(\010\"@\n\017ListConsumer" +
      "sRq\022\017\n\007cluster\030\001 \001(\t\022\r\n\005topic\030\002 \001(\t\022\r\n\005g" +
      "roup\030\003 \001(\t\"(\n\022ConsumerPartitions\022\022\n\npart" +
      "itions\030\001 \003(\005\"\212\001\n\016ConsumerGroups\0221\n\tconsu" +
      "mers\030\001 \003(\0132\036.ConsumerGroups.ConsumersEnt" +
      "ry\032E\n\016ConsumersEntry\022\013\n\003key\030\001 \001(\t\022\"\n\005val" +
      "ue\030\002 \001(\0132\023.ConsumerPartitions:\0028\001\"\177\n\017Lis" +
      "tConsumersRs\022,\n\006groups\030\001 \003(\0132\034.ListConsu" +
      "mersRs.GroupsEntry\032>\n\013GroupsEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\036\n\005value\030\002 \001(\0132\017.ConsumerGroups:\002" +
      "8\001\"`\n\014SetOffsetsRq\022\017\n\007cluster\030\001 \001(\t\022\r\n\005t" +
      "opic\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022!\n\007offsets\030\004 \003" +
      "(\0132\020.PartitionOffset\"\016\n\014SetOffsetsRs2\360\002\n" +
      "\020KafkaPixyService\022\035\n\007Produce\022\007.ProdRq\032\007." +
      "ProdRs\"\000\022%\n\013ConsumeNAck\022\013.ConsNAckRq\032\007.C" +
      "onsRs\"\000\022\027\n\003Ack\022\006.AckRq\032\006.AckRs\"\000\022,\n\nGetO" +
      "ffsets\022\r.GetOffsetsRq\032\r.GetOffsetsRs\"\000\022," +
      "\n\nSetOffsets\022\r.SetOffsetsRq\032\r.SetOffsets" +
      "Rs\"\000\022*\n\nListTopics\022\014.ListTopicRq\032\014.ListT" +
      "opicRs\"\000\0225\n\rListConsumers\022\020.ListConsumer" +
      "sRq\032\020.ListConsumersRs\"\000\022>\n\020GetTopicMetad" +
      "ata\022\023.GetTopicMetadataRq\032\023.GetTopicMetad" +
      "ataRs\"\000B\023\n\014com.csvw.libP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RecordHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RecordHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RecordHeader_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ProdRq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ProdRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProdRq_descriptor,
        new String[] { "Cluster", "Topic", "KeyValue", "KeyUndefined", "Message", "AsyncMode", "Headers", });
    internal_static_ProdRs_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProdRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProdRs_descriptor,
        new String[] { "Partition", "Offset", });
    internal_static_ConsNAckRq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ConsNAckRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsNAckRq_descriptor,
        new String[] { "Cluster", "Topic", "Group", "NoAck", "AutoAck", "AckPartition", "AckOffset", });
    internal_static_ConsRs_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ConsRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsRs_descriptor,
        new String[] { "Partition", "Offset", "KeyValue", "KeyUndefined", "Message", "Headers", });
    internal_static_AckRq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_AckRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckRq_descriptor,
        new String[] { "Cluster", "Topic", "Group", "Partition", "Offset", });
    internal_static_AckRs_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_AckRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckRs_descriptor,
        new String[] { });
    internal_static_PartitionOffset_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_PartitionOffset_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartitionOffset_descriptor,
        new String[] { "Partition", "Begin", "End", "Count", "Offset", "Lag", "Metadata", "SparseAcks", });
    internal_static_GetOffsetsRq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_GetOffsetsRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetOffsetsRq_descriptor,
        new String[] { "Cluster", "Topic", "Group", });
    internal_static_GetOffsetsRs_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GetOffsetsRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetOffsetsRs_descriptor,
        new String[] { "Offsets", });
    internal_static_PartitionMetadata_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_PartitionMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartitionMetadata_descriptor,
        new String[] { "Partition", "Leader", "Replicas", "Isr", });
    internal_static_GetTopicMetadataRq_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_GetTopicMetadataRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTopicMetadataRq_descriptor,
        new String[] { "Cluster", "Topic", "WithPartitions", });
    internal_static_GetTopicMetadataRs_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_GetTopicMetadataRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTopicMetadataRs_descriptor,
        new String[] { "Version", "Config", "Partitions", });
    internal_static_GetTopicMetadataRs_ConfigEntry_descriptor =
      internal_static_GetTopicMetadataRs_descriptor.getNestedTypes().get(0);
    internal_static_GetTopicMetadataRs_ConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetTopicMetadataRs_ConfigEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ListTopicRs_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_ListTopicRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListTopicRs_descriptor,
        new String[] { "Topics", });
    internal_static_ListTopicRs_TopicsEntry_descriptor =
      internal_static_ListTopicRs_descriptor.getNestedTypes().get(0);
    internal_static_ListTopicRs_TopicsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListTopicRs_TopicsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ListTopicRq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_ListTopicRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListTopicRq_descriptor,
        new String[] { "Cluster", "WithPartitions", });
    internal_static_ListConsumersRq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_ListConsumersRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListConsumersRq_descriptor,
        new String[] { "Cluster", "Topic", "Group", });
    internal_static_ConsumerPartitions_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_ConsumerPartitions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsumerPartitions_descriptor,
        new String[] { "Partitions", });
    internal_static_ConsumerGroups_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_ConsumerGroups_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsumerGroups_descriptor,
        new String[] { "Consumers", });
    internal_static_ConsumerGroups_ConsumersEntry_descriptor =
      internal_static_ConsumerGroups_descriptor.getNestedTypes().get(0);
    internal_static_ConsumerGroups_ConsumersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConsumerGroups_ConsumersEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_ListConsumersRs_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_ListConsumersRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListConsumersRs_descriptor,
        new String[] { "Groups", });
    internal_static_ListConsumersRs_GroupsEntry_descriptor =
      internal_static_ListConsumersRs_descriptor.getNestedTypes().get(0);
    internal_static_ListConsumersRs_GroupsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListConsumersRs_GroupsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_SetOffsetsRq_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_SetOffsetsRq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetOffsetsRq_descriptor,
        new String[] { "Cluster", "Topic", "Group", "Offsets", });
    internal_static_SetOffsetsRs_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_SetOffsetsRs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SetOffsetsRs_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
