// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

public interface ListTopicRsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListTopicRs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .GetTopicMetadataRs&gt; topics = 1;</code>
   */
  int getTopicsCount();
  /**
   * <code>map&lt;string, .GetTopicMetadataRs&gt; topics = 1;</code>
   */
  boolean containsTopics(
          String key);
  /**
   * Use {@link #getTopicsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, GetTopicMetadataRs>
  getTopics();
  /**
   * <code>map&lt;string, .GetTopicMetadataRs&gt; topics = 1;</code>
   */
  java.util.Map<String, GetTopicMetadataRs>
  getTopicsMap();
  /**
   * <code>map&lt;string, .GetTopicMetadataRs&gt; topics = 1;</code>
   */

  GetTopicMetadataRs getTopicsOrDefault(
          String key,
          GetTopicMetadataRs defaultValue);
  /**
   * <code>map&lt;string, .GetTopicMetadataRs&gt; topics = 1;</code>
   */

  GetTopicMetadataRs getTopicsOrThrow(
          String key);
}
