// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

public interface ListConsumersRqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListConsumersRq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The cluster.
   */
  String getCluster();
  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The bytes for cluster.
   */
  com.google.protobuf.ByteString
      getClusterBytes();

  /**
   * <pre>
   * Name of a topic
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  String getTopic();
  /**
   * <pre>
   * Name of a topic
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <pre>
   * If non empty, return only the specified group in the result
   * </pre>
   *
   * <code>string group = 3;</code>
   * @return The group.
   */
  String getGroup();
  /**
   * <pre>
   * If non empty, return only the specified group in the result
   * </pre>
   *
   * <code>string group = 3;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();
}
