// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

public interface ListTopicRqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListTopicRq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The cluster.
   */
  String getCluster();
  /**
   * <pre>
   * Name of a Kafka cluster
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The bytes for cluster.
   */
  com.google.protobuf.ByteString
      getClusterBytes();

  /**
   * <pre>
   * Should include partition metadata
   * </pre>
   *
   * <code>bool with_partitions = 2;</code>
   * @return The withPartitions.
   */
  boolean getWithPartitions();
}
