// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafkapixy.proto

package com.csvw.lib;

/**
 * Protobuf type {@code ProdRq}
 */
public final class ProdRq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ProdRq)
    ProdRqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProdRq.newBuilder() to construct.
  private ProdRq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProdRq() {
    cluster_ = "";
    topic_ = "";
    keyValue_ = com.google.protobuf.ByteString.EMPTY;
    message_ = com.google.protobuf.ByteString.EMPTY;
    headers_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProdRq();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProdRq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            cluster_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 26: {

            keyValue_ = input.readBytes();
            break;
          }
          case 32: {

            keyUndefined_ = input.readBool();
            break;
          }
          case 42: {

            message_ = input.readBytes();
            break;
          }
          case 48: {

            asyncMode_ = input.readBool();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              headers_ = new java.util.ArrayList<RecordHeader>();
              mutable_bitField0_ |= 0x00000001;
            }
            headers_.add(
                input.readMessage(RecordHeader.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        headers_ = java.util.Collections.unmodifiableList(headers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Kafkapixy.internal_static_ProdRq_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Kafkapixy.internal_static_ProdRq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProdRq.class, ProdRq.Builder.class);
  }

  public static final int CLUSTER_FIELD_NUMBER = 1;
  private volatile Object cluster_;
  /**
   * <pre>
   * Name of a Kafka cluster to operate on.
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The cluster.
   */
  @Override
  public String getCluster() {
    Object ref = cluster_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cluster_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of a Kafka cluster to operate on.
   * </pre>
   *
   * <code>string cluster = 1;</code>
   * @return The bytes for cluster.
   */
  @Override
  public com.google.protobuf.ByteString
      getClusterBytes() {
    Object ref = cluster_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cluster_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC_FIELD_NUMBER = 2;
  private volatile Object topic_;
  /**
   * <pre>
   * Name of a topic to produce to.
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  @Override
  public String getTopic() {
    Object ref = topic_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of a topic to produce to.
   * </pre>
   *
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  @Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    Object ref = topic_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_VALUE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString keyValue_;
  /**
   * <pre>
   * Hash of the key is used to determine the partition to produce to. By
   * default it is an empty array which is a valid key, unless key_undefined
   * is set to true and then a random partition is selected.
   * </pre>
   *
   * <code>bytes key_value = 3;</code>
   * @return The keyValue.
   */
  @Override
  public com.google.protobuf.ByteString getKeyValue() {
    return keyValue_;
  }

  public static final int KEY_UNDEFINED_FIELD_NUMBER = 4;
  private boolean keyUndefined_;
  /**
   * <pre>
   * If true then the message is written to a random partition, otherwise
   * hash of key_value is used to determine the partition.
   * </pre>
   *
   * <code>bool key_undefined = 4;</code>
   * @return The keyUndefined.
   */
  @Override
  public boolean getKeyUndefined() {
    return keyUndefined_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString message_;
  /**
   * <pre>
   * Message body.
   * </pre>
   *
   * <code>bytes message = 5;</code>
   * @return The message.
   */
  @Override
  public com.google.protobuf.ByteString getMessage() {
    return message_;
  }

  public static final int ASYNC_MODE_FIELD_NUMBER = 6;
  private boolean asyncMode_;
  /**
   * <pre>
   * If true then the method returns immediately after Kafka-Pixy gets the
   * produce request, and the message is written to Kafka asynchronously.
   * In that case partition and offset returned in response should be ignored.
   * If false, then a response is returned in accordance with the
   * producer.required_acks parameter, that can be one of:
   *  * no_response:    the response is returned as soon as a produce request
   *                    is delivered to a partition leader Kafka broker.
   *  * wait_for_local: the response is returned as soon as data is written
   *                    to the disk by a partition leader Kafka broker.
   *  * wait_for_all:   the response is returned after all in-sync replicas
   *                    have data committed to disk.
   * </pre>
   *
   * <code>bool async_mode = 6;</code>
   * @return The asyncMode.
   */
  @Override
  public boolean getAsyncMode() {
    return asyncMode_;
  }

  public static final int HEADERS_FIELD_NUMBER = 7;
  private java.util.List<RecordHeader> headers_;
  /**
   * <pre>
   * Headers to include with the published message
   * </pre>
   *
   * <code>repeated .RecordHeader headers = 7;</code>
   */
  @Override
  public java.util.List<RecordHeader> getHeadersList() {
    return headers_;
  }
  /**
   * <pre>
   * Headers to include with the published message
   * </pre>
   *
   * <code>repeated .RecordHeader headers = 7;</code>
   */
  @Override
  public java.util.List<? extends RecordHeaderOrBuilder>
      getHeadersOrBuilderList() {
    return headers_;
  }
  /**
   * <pre>
   * Headers to include with the published message
   * </pre>
   *
   * <code>repeated .RecordHeader headers = 7;</code>
   */
  @Override
  public int getHeadersCount() {
    return headers_.size();
  }
  /**
   * <pre>
   * Headers to include with the published message
   * </pre>
   *
   * <code>repeated .RecordHeader headers = 7;</code>
   */
  @Override
  public RecordHeader getHeaders(int index) {
    return headers_.get(index);
  }
  /**
   * <pre>
   * Headers to include with the published message
   * </pre>
   *
   * <code>repeated .RecordHeader headers = 7;</code>
   */
  @Override
  public RecordHeaderOrBuilder getHeadersOrBuilder(
      int index) {
    return headers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClusterBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cluster_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, topic_);
    }
    if (!keyValue_.isEmpty()) {
      output.writeBytes(3, keyValue_);
    }
    if (keyUndefined_ != false) {
      output.writeBool(4, keyUndefined_);
    }
    if (!message_.isEmpty()) {
      output.writeBytes(5, message_);
    }
    if (asyncMode_ != false) {
      output.writeBool(6, asyncMode_);
    }
    for (int i = 0; i < headers_.size(); i++) {
      output.writeMessage(7, headers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClusterBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cluster_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, topic_);
    }
    if (!keyValue_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, keyValue_);
    }
    if (keyUndefined_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, keyUndefined_);
    }
    if (!message_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, message_);
    }
    if (asyncMode_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, asyncMode_);
    }
    for (int i = 0; i < headers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, headers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProdRq)) {
      return super.equals(obj);
    }
    ProdRq other = (ProdRq) obj;

    if (!getCluster()
        .equals(other.getCluster())) return false;
    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getKeyValue()
        .equals(other.getKeyValue())) return false;
    if (getKeyUndefined()
        != other.getKeyUndefined()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getAsyncMode()
        != other.getAsyncMode()) return false;
    if (!getHeadersList()
        .equals(other.getHeadersList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLUSTER_FIELD_NUMBER;
    hash = (53 * hash) + getCluster().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + KEY_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getKeyValue().hashCode();
    hash = (37 * hash) + KEY_UNDEFINED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getKeyUndefined());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + ASYNC_MODE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAsyncMode());
    if (getHeadersCount() > 0) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getHeadersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ProdRq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProdRq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProdRq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProdRq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProdRq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProdRq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProdRq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProdRq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProdRq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ProdRq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProdRq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProdRq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ProdRq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ProdRq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ProdRq)
      ProdRqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Kafkapixy.internal_static_ProdRq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Kafkapixy.internal_static_ProdRq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProdRq.class, ProdRq.Builder.class);
    }

    // Construct using com.csvw.lib.ProdRq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHeadersFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      cluster_ = "";

      topic_ = "";

      keyValue_ = com.google.protobuf.ByteString.EMPTY;

      keyUndefined_ = false;

      message_ = com.google.protobuf.ByteString.EMPTY;

      asyncMode_ = false;

      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        headersBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Kafkapixy.internal_static_ProdRq_descriptor;
    }

    @Override
    public ProdRq getDefaultInstanceForType() {
      return ProdRq.getDefaultInstance();
    }

    @Override
    public ProdRq build() {
      ProdRq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ProdRq buildPartial() {
      ProdRq result = new ProdRq(this);
      int from_bitField0_ = bitField0_;
      result.cluster_ = cluster_;
      result.topic_ = topic_;
      result.keyValue_ = keyValue_;
      result.keyUndefined_ = keyUndefined_;
      result.message_ = message_;
      result.asyncMode_ = asyncMode_;
      if (headersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.headers_ = headers_;
      } else {
        result.headers_ = headersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProdRq) {
        return mergeFrom((ProdRq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProdRq other) {
      if (other == ProdRq.getDefaultInstance()) return this;
      if (!other.getCluster().isEmpty()) {
        cluster_ = other.cluster_;
        onChanged();
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (other.getKeyValue() != com.google.protobuf.ByteString.EMPTY) {
        setKeyValue(other.getKeyValue());
      }
      if (other.getKeyUndefined() != false) {
        setKeyUndefined(other.getKeyUndefined());
      }
      if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
        setMessage(other.getMessage());
      }
      if (other.getAsyncMode() != false) {
        setAsyncMode(other.getAsyncMode());
      }
      if (headersBuilder_ == null) {
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
      } else {
        if (!other.headers_.isEmpty()) {
          if (headersBuilder_.isEmpty()) {
            headersBuilder_.dispose();
            headersBuilder_ = null;
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            headersBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeadersFieldBuilder() : null;
          } else {
            headersBuilder_.addAllMessages(other.headers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProdRq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProdRq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object cluster_ = "";
    /**
     * <pre>
     * Name of a Kafka cluster to operate on.
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @return The cluster.
     */
    public String getCluster() {
      Object ref = cluster_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cluster_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Name of a Kafka cluster to operate on.
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @return The bytes for cluster.
     */
    public com.google.protobuf.ByteString
        getClusterBytes() {
      Object ref = cluster_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cluster_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of a Kafka cluster to operate on.
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @param value The cluster to set.
     * @return This builder for chaining.
     */
    public Builder setCluster(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      cluster_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a Kafka cluster to operate on.
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCluster() {

      cluster_ = getDefaultInstance().getCluster();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a Kafka cluster to operate on.
     * </pre>
     *
     * <code>string cluster = 1;</code>
     * @param value The bytes for cluster to set.
     * @return This builder for chaining.
     */
    public Builder setClusterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      cluster_ = value;
      onChanged();
      return this;
    }

    private Object topic_ = "";
    /**
     * <pre>
     * Name of a topic to produce to.
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @return The topic.
     */
    public String getTopic() {
      Object ref = topic_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Name of a topic to produce to.
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of a topic to produce to.
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a topic to produce to.
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {

      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of a topic to produce to.
     * </pre>
     *
     * <code>string topic = 2;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      topic_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString keyValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Hash of the key is used to determine the partition to produce to. By
     * default it is an empty array which is a valid key, unless key_undefined
     * is set to true and then a random partition is selected.
     * </pre>
     *
     * <code>bytes key_value = 3;</code>
     * @return The keyValue.
     */
    @Override
    public com.google.protobuf.ByteString getKeyValue() {
      return keyValue_;
    }
    /**
     * <pre>
     * Hash of the key is used to determine the partition to produce to. By
     * default it is an empty array which is a valid key, unless key_undefined
     * is set to true and then a random partition is selected.
     * </pre>
     *
     * <code>bytes key_value = 3;</code>
     * @param value The keyValue to set.
     * @return This builder for chaining.
     */
    public Builder setKeyValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      keyValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hash of the key is used to determine the partition to produce to. By
     * default it is an empty array which is a valid key, unless key_undefined
     * is set to true and then a random partition is selected.
     * </pre>
     *
     * <code>bytes key_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyValue() {

      keyValue_ = getDefaultInstance().getKeyValue();
      onChanged();
      return this;
    }

    private boolean keyUndefined_ ;
    /**
     * <pre>
     * If true then the message is written to a random partition, otherwise
     * hash of key_value is used to determine the partition.
     * </pre>
     *
     * <code>bool key_undefined = 4;</code>
     * @return The keyUndefined.
     */
    @Override
    public boolean getKeyUndefined() {
      return keyUndefined_;
    }
    /**
     * <pre>
     * If true then the message is written to a random partition, otherwise
     * hash of key_value is used to determine the partition.
     * </pre>
     *
     * <code>bool key_undefined = 4;</code>
     * @param value The keyUndefined to set.
     * @return This builder for chaining.
     */
    public Builder setKeyUndefined(boolean value) {

      keyUndefined_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true then the message is written to a random partition, otherwise
     * hash of key_value is used to determine the partition.
     * </pre>
     *
     * <code>bool key_undefined = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyUndefined() {

      keyUndefined_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Message body.
     * </pre>
     *
     * <code>bytes message = 5;</code>
     * @return The message.
     */
    @Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }
    /**
     * <pre>
     * Message body.
     * </pre>
     *
     * <code>bytes message = 5;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Message body.
     * </pre>
     *
     * <code>bytes message = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {

      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }

    private boolean asyncMode_ ;
    /**
     * <pre>
     * If true then the method returns immediately after Kafka-Pixy gets the
     * produce request, and the message is written to Kafka asynchronously.
     * In that case partition and offset returned in response should be ignored.
     * If false, then a response is returned in accordance with the
     * producer.required_acks parameter, that can be one of:
     *  * no_response:    the response is returned as soon as a produce request
     *                    is delivered to a partition leader Kafka broker.
     *  * wait_for_local: the response is returned as soon as data is written
     *                    to the disk by a partition leader Kafka broker.
     *  * wait_for_all:   the response is returned after all in-sync replicas
     *                    have data committed to disk.
     * </pre>
     *
     * <code>bool async_mode = 6;</code>
     * @return The asyncMode.
     */
    @Override
    public boolean getAsyncMode() {
      return asyncMode_;
    }
    /**
     * <pre>
     * If true then the method returns immediately after Kafka-Pixy gets the
     * produce request, and the message is written to Kafka asynchronously.
     * In that case partition and offset returned in response should be ignored.
     * If false, then a response is returned in accordance with the
     * producer.required_acks parameter, that can be one of:
     *  * no_response:    the response is returned as soon as a produce request
     *                    is delivered to a partition leader Kafka broker.
     *  * wait_for_local: the response is returned as soon as data is written
     *                    to the disk by a partition leader Kafka broker.
     *  * wait_for_all:   the response is returned after all in-sync replicas
     *                    have data committed to disk.
     * </pre>
     *
     * <code>bool async_mode = 6;</code>
     * @param value The asyncMode to set.
     * @return This builder for chaining.
     */
    public Builder setAsyncMode(boolean value) {

      asyncMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true then the method returns immediately after Kafka-Pixy gets the
     * produce request, and the message is written to Kafka asynchronously.
     * In that case partition and offset returned in response should be ignored.
     * If false, then a response is returned in accordance with the
     * producer.required_acks parameter, that can be one of:
     *  * no_response:    the response is returned as soon as a produce request
     *                    is delivered to a partition leader Kafka broker.
     *  * wait_for_local: the response is returned as soon as data is written
     *                    to the disk by a partition leader Kafka broker.
     *  * wait_for_all:   the response is returned after all in-sync replicas
     *                    have data committed to disk.
     * </pre>
     *
     * <code>bool async_mode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsyncMode() {

      asyncMode_ = false;
      onChanged();
      return this;
    }

    private java.util.List<RecordHeader> headers_ =
      java.util.Collections.emptyList();
    private void ensureHeadersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        headers_ = new java.util.ArrayList<RecordHeader>(headers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        RecordHeader, RecordHeader.Builder, RecordHeaderOrBuilder> headersBuilder_;

    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public java.util.List<RecordHeader> getHeadersList() {
      if (headersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(headers_);
      } else {
        return headersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public int getHeadersCount() {
      if (headersBuilder_ == null) {
        return headers_.size();
      } else {
        return headersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public RecordHeader getHeaders(int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);
      } else {
        return headersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder setHeaders(
        int index, RecordHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
      } else {
        headersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder setHeaders(
        int index, RecordHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.set(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder addHeaders(RecordHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
      } else {
        headersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder addHeaders(
        int index, RecordHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(index, value);
        onChanged();
      } else {
        headersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder addHeaders(
        RecordHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder addHeaders(
        int index, RecordHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder addAllHeaders(
        Iterable<? extends RecordHeader> values) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, headers_);
        onChanged();
      } else {
        headersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder clearHeaders() {
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        headersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public Builder removeHeaders(int index) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.remove(index);
        onChanged();
      } else {
        headersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public RecordHeader.Builder getHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public RecordHeaderOrBuilder getHeadersOrBuilder(
        int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);  } else {
        return headersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public java.util.List<? extends RecordHeaderOrBuilder>
         getHeadersOrBuilderList() {
      if (headersBuilder_ != null) {
        return headersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(headers_);
      }
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public RecordHeader.Builder addHeadersBuilder() {
      return getHeadersFieldBuilder().addBuilder(
          RecordHeader.getDefaultInstance());
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public RecordHeader.Builder addHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().addBuilder(
          index, RecordHeader.getDefaultInstance());
    }
    /**
     * <pre>
     * Headers to include with the published message
     * </pre>
     *
     * <code>repeated .RecordHeader headers = 7;</code>
     */
    public java.util.List<RecordHeader.Builder>
         getHeadersBuilderList() {
      return getHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        RecordHeader, RecordHeader.Builder, RecordHeaderOrBuilder>
        getHeadersFieldBuilder() {
      if (headersBuilder_ == null) {
        headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            RecordHeader, RecordHeader.Builder, RecordHeaderOrBuilder>(
                headers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        headers_ = null;
      }
      return headersBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ProdRq)
  }

  // @@protoc_insertion_point(class_scope:ProdRq)
  private static final ProdRq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProdRq();
  }

  public static ProdRq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProdRq>
      PARSER = new com.google.protobuf.AbstractParser<ProdRq>() {
    @Override
    public ProdRq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProdRq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProdRq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ProdRq> getParserForType() {
    return PARSER;
  }

  @Override
  public ProdRq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

